export const CHECK_AUTHORIZATION_REQUEST = 'CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_SUCCESS = 'CHECK_AUTHORIZATION_SUCCESS';
export const CHECK_AUTHORIZATION_FAIL = 'CHECK_AUTHORIZATION_FAIL';

export const LOGOUT = 'LOGOUT';
export const USER_INFO_STORAGE_KEY = 'userInfo';
export const HEVO_TOKEN_COOKIE_KEY = 'htt';

export const LOGIN_FAIL = 'LOGIN_FAIL';
